// Code generated by yaml2go on 2022-08-14T18:50:47Z; DO NOT EDIT.

// Open Adventure - a clone of Open Adventure written in Go
// Copyright (c) 2022 Michael D Henderson
// SPDX-License-Identifier: BSD-2-clause

package state

// ArbitraryMessages is an ordered map of messages
// Use `Seq` to access sequentially or `Map` to access by key.
// Note that no message string ends with a new-line!
type ArbitraryMessages struct {
    Seq []string           // sequential accessor
    Map map[string]string  // tag accessor
}

// generateArbitraryMessages returns the initial arbitrary message state
func generateArbitraryMessages() *ArbitraryMessages {
    arbitraryMessages := &ArbitraryMessages{
        Map: make(map[string]string),
    }

    tag := "NO_MESSAGE"
    arbitraryMessages.Map[tag] = ""
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)

    tag = "CAVE_NEARBY"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "Somewhere nearby is Colossal Cave, where others have found fortunes in\ntreasure and gold, though it is rumored that some who enter are never\nseen again.  Magic is said to work in the cave.  I will be your eyes\nand hands.  Direct me with commands of 1 or 2 words.  I should warn\nyou that I look at only the first five letters of each word, so you'll\nhave to enter \"northeast\" as \"ne\" to distinguish it from \"north\".\nYou can type \"help\" for some general hints.  For information on how\nto end your adventure, scoring, etc., type \"info\".\n\\t\\t\\t      - - -\nThis program was originally developed by Willie Crowther.  Most of the\nfeatures of the current program were added by Don Woods."

    tag = "DWARF_BLOCK"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "A little dwarf with a big knife blocks your way."

    tag = "DWARF_RAN"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "A little dwarf just walked around a corner, saw you, threw a little\naxe at you which missed, cursed, and ran away."

    tag = "DWARF_PACK"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "There are %d threatening little dwarves in the room with you."

    tag = "DWARF_SINGLE"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "There is a threatening little dwarf in the room with you!"

    tag = "KNIFE_THROWN"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "One sharp nasty knife is thrown at you!"

    tag = "SAYS_PLUGH"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "A hollow voice says \"PLUGH\"."

    tag = "GETS_YOU"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "It gets you!"

    tag = "MISSES_YOU"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "It misses!"

    tag = "UNSURE_FACING"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "I am unsure how you are facing.  Use compass points or nearby objects."

    tag = "NO_INOUT_HERE"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "I don't know in from out here.  Use compass points or name something\nin the general direction you want to go."

    tag = "CANT_APPLY"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "I don't know how to apply that word here."

    tag = "AM_GAME"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "I'm game.  Would you care to explain how?"

    tag = "NO_MORE_DETAIL"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "Sorry, but I am not allowed to give more detail.  I will repeat the\nlong description of your location."

    tag = "PITCH_DARK"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "It is now pitch dark.  If you proceed you will likely fall into a pit."

    tag = "W_IS_WEST"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "If you prefer, simply type w rather than west."

    tag = "REALLY_QUIT"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "Do you really want to quit now?"

    tag = "PIT_FALL"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "You fell into a pit and broke every bone in your body!"

    tag = "ALREADY_CARRYING"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "You are already carrying it!"

    tag = "YOU_JOKING"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "You can't be serious!"

    tag = "BIRD_EVADES"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The bird seemed unafraid at first, but as you approach it becomes\ndisturbed and you cannot catch it."

    tag = "CANNOT_CARRY"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "You can catch the bird, but you cannot carry it."

    tag = "NOTHING_LOCKED"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "There is nothing here with a lock!"

    tag = "ARENT_CARRYING"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "You aren't carrying it!"

    tag = "BIRD_ATTACKS"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The little bird attacks the green snake, and in an astounding flurry\ndrives the snake away."

    tag = "NO_KEYS"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "You have no keys!"

    tag = "NO_LOCK"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "It has no lock."

    tag = "NOT_LOCKABLE"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "I don't know how to lock or unlock such a thing."

    tag = "ALREADY_LOCKED"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "It was already locked."

    tag = "ALREADY_UNLOCKED"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "It was already unlocked."

    tag = "BEAR_BLOCKS"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "There is no way to get past the bear to unlock the chain, which is\nprobably just as well."

    tag = "NOTHING_HAPPENS"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "Nothing happens."

    tag = "WHERE_QUERY"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "Where?"

    tag = "NO_TARGET"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "There is nothing here to attack."

    tag = "BIRD_DEAD"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The little bird is now dead.  Its body disappears."

    tag = "SNAKE_WARNING"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "Attacking the snake both doesn't work and is very dangerous."

    tag = "KILLED_DWARF"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "You killed a little dwarf."

    tag = "DWARF_DODGES"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "You attack a little dwarf, but he dodges out of the way."

    tag = "BARE_HANDS_QUERY"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "With what?  Your bare hands?"

    tag = "BAD_DIRECTION"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "There is no way to go that direction."

    tag = "TWO_WORDS"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "Please stick to 1- and 2-word commands."

    tag = "OK_MAN"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "OK"

    tag = "CANNOT_UNLOCK"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "You can't unlock the keys."

    tag = "FUTILE_CRAWL"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "You have crawled around in some little holes and wound up back in the\nmain passage."

    tag = "FOLLOW_STREAM"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "I don't know where the cave is, but hereabouts no stream can run on\nthe surface for long.  I would try the stream."

    tag = "NEED_DETAIL"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "I need more detailed instructions to do that."

    tag = "NEARBY"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "I can only tell you what you see as you move about and manipulate\nthings.  I cannot tell you where remote things are."

    tag = "OGRE_SNARL"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The ogre snarls and shoves you back."

    tag = "HUH_MAN"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "Huh?"

    tag = "WELCOME_YOU"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "Welcome to Adventure!!  Would you like instructions?"

    tag = "REQUIRES_DYNAMITE"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "Blasting requires dynamite."

    tag = "FEET_WET"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "Your feet are now wet."

    tag = "LOST_APPETITE"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "I think I just lost my appetite."

    tag = "THANKS_DELICIOUS"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "Thank you, it was delicious!"

    tag = "PECULIAR_NOTHING"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "Peculiar.  Nothing unexpected happens."

    tag = "GROUND_WET"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "Your bottle is empty and the ground is wet."

    tag = "CANT_POUR"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "You can't pour that."

    tag = "WHICH_WAY"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "Which way?"

    tag = "FORGOT_PATH"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "Sorry, but I no longer seem to remember how it was you got here."

    tag = "CARRY_LIMIT"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "You can't carry anything more.  You'll have to drop something first."

    tag = "GRATE_NOWAY"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "You can't go through a locked steel grate!"

    tag = "YOU_HAVEIT"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "I believe what you want is right here with you."

    tag = "DONT_FIT"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "You don't fit through a two-inch slit!"

    tag = "CROSS_BRIDGE"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "I respectfully suggest you go across the bridge instead of jumping."

    tag = "NO_CROSS"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "There is no way across the fissure."

    tag = "NO_CARRY"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "You're not carrying anything."

    tag = "NOW_HOLDING"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "You are currently holding the following:"

    tag = "BIRD_PINING"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "It's not hungry (it's merely pinin' for the fjords).  Besides, you\nhave no bird seed."

    tag = "BIRD_DEVOURED"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The snake has now devoured your bird."

    tag = "NOTHING_EDIBLE"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "There's nothing here it wants to eat (except perhaps you)."

    tag = "REALLY_MAD"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "You fool, dwarves eat only coal!  Now you've made him *REALLY* mad!!"

    tag = "NO_CONTAINER"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "You have nothing in which to carry it."

    tag = "BOTTLE_FULL"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "Your bottle is already full."

    tag = "NO_LIQUID"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "There is nothing here with which to fill the bottle."

    tag = "RIDICULOUS_ATTEMPT"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "Don't be ridiculous!"

    tag = "RUSTY_DOOR"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The door is extremely rusty and refuses to open."

    tag = "SHAKING_LEAVES"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The plant indignantly shakes the oil off its leaves and asks, \"Water?\""

    tag = "DEEP_ROOTS"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The plant has exceptionally deep roots and cannot be pulled free."

    tag = "KNIVES_VANISH"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The dwarves' knives vanish as they strike the walls of the cave."

    tag = "MUST_DROP"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "Something you're carrying won't fit through the tunnel with you.\nYou'd best take inventory and drop something."

    tag = "CLAM_BLOCKER"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "You can't fit this five-foot clam through that little passage!"

    tag = "OYSTER_BLOCKER"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "You can't fit this five-foot oyster through that little passage!"

    tag = "DROP_CLAM"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "I advise you to put down the clam before opening it.  >STRAIN!<"

    tag = "DROP_OYSTER"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "I advise you to put down the oyster before opening it.  >WRENCH!<"

    tag = "CLAM_OPENER"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "You don't have anything strong enough to open the clam."

    tag = "OYSTER_OPENER"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "You don't have anything strong enough to open the oyster."

    tag = "PEARL_FALLS"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "A glistening pearl falls out of the clam and rolls away.  Goodness,\nthis must really be an oyster.  (I never was very good at identifying\nbivalves.)  Whatever it is, it has now snapped shut again."

    tag = "OYSTER_OPENS"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The oyster creaks open, revealing nothing but oyster inside.  It\npromptly snaps shut again."

    tag = "WAY_BLOCKED"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "You have crawled around in some little holes and found your way\nblocked by a recent cave-in.  You are now back in the main passage."

    tag = "PIRATE_RUSTLES"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "There are faint rustling noises from the darkness behind you."

    tag = "PIRATE_POUNCES"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "Out from the shadows behind you pounces a bearded pirate!  \"Har, har,\"\nhe chortles, \"I'll just take all this booty and hide it away with me\nchest deep in the maze!\"  He snatches your treasure and vanishes into\nthe gloom."

    tag = "CAVE_CLOSING"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "A sepulchral voice reverberating through the cave, says, \"Cave closing\nsoon.  All adventurers exit immediately through main office.\""

    tag = "EXIT_CLOSED"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "A mysterious recorded voice groans into life and announces:\n   \"This exit is closed.  Please leave via main office.\""

    tag = "DEATH_CLOSING"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "It looks as though you're dead.  Well, seeing as how it's so close to\nclosing time anyway, I think we'll just call it a day."

    tag = "CAVE_CLOSED"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The sepulchral voice intones, \"The cave is now closed.\"  As the echoes\nfade, there is a blinding flash of light (and a small puff of orange\nsmoke). . . .    As your eyes refocus, you look around and find..."

    tag = "VICTORY_MESSAGE"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "There is a loud explosion, and a twenty-foot hole appears in the far\nwall, burying the dwarves in the rubble.  You march through the hole\nand find yourself in the main office, where a cheering band of\nfriendly elves carry the conquering adventurer off into the sunset."

    tag = "DEFEAT_MESSAGE"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "There is a loud explosion, and a twenty-foot hole appears in the far\nwall, burying the snakes in the rubble.  A river of molten lava pours\nin through the hole, destroying everything in its path, including you!"

    tag = "SPLATTER_MESSAGE"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "There is a loud explosion, and you are suddenly splashed across the\nwalls of the room."

    tag = "DWARVES_AWAKEN"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The resulting ruckus has awakened the dwarves.  There are now several\nthreatening little dwarves in the room with you!  Most of them throw\nknives at you!  All of them get you!"

    tag = "UNHAPPY_BIRD"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "Oh, leave the poor unhappy bird alone."

    tag = "NEEDED_NEARBY"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "I daresay whatever you want is around here somewhere."

    tag = "NOT_CONNECTED"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "You can't get there from here."

    tag = "TAME_BEAR"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "You are being followed by a very large, tame bear."

    tag = "WITHOUT_SUSPENDS"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "Now let's see you do it without suspending in mid-Adventure."

    tag = "FILL_INVALID"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "There is nothing here with which to fill it."

    tag = "SHATTER_VASE"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The sudden change in temperature has delicately shattered the vase."

    tag = "BEYOND_POWER"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "It is beyond your power to do that."

    tag = "NOT_KNOWHOW"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "I don't know how."

    tag = "TOO_FAR"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "It is too far up for you to reach."

    tag = "DWARF_SMOKE"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "You killed a little dwarf.  The body vanishes in a cloud of greasy\nblack smoke."

    tag = "SHELL_IMPERVIOUS"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The shell is very strong and is impervious to attack."

    tag = "START_OVER"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "What's the matter, can't you read?  Now you'd best start over."

    tag = "DRAGON_SCALES"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The axe bounces harmlessly off the dragon's thick scales."

    tag = "NASTY_DRAGON"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The dragon looks rather nasty.  You'd best not try to get by."

    tag = "BIRD_BURNT"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The little bird attacks the green dragon, and in an astounding flurry\ngets burnt to a cinder.  The ashes blow away."

    tag = "BRIEF_CONFIRM"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "Okay, from now on I'll only describe a place in full the first time\nyou come to it.  To get the full description, say \"look\"."

    tag = "ROCKY_TROLL"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "Trolls are close relatives with the rocks and have skin as tough as\nthat of a rhinoceros.  The troll fends off your blows effortlessly."

    tag = "TROLL_RETURNS"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The troll deftly catches the axe, examines it carefully, and tosses it\nback, declaring, \"Good workmanship, but it's not valuable enough.\""

    tag = "TROLL_SATISFIED"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The troll catches your treasure and scurries away out of sight."

    tag = "TROLL_BLOCKS"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The troll refuses to let you cross."

    tag = "BRIDGE_GONE"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "There is no longer any way across the chasm."

    tag = "BEAR_HANDS"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "With what?  Your bare hands?  Against *HIS* bear hands??"

    tag = "BEAR_CONFUSED"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The bear is confused; he only wants to be your friend."

    tag = "ALREADY_DEAD"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "For crying out loud, the poor thing is already dead!"

    tag = "BEAR_CHAINED"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The bear is still chained to the wall."

    tag = "STILL_LOCKED"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The chain is still locked."

    tag = "CHAIN_UNLOCKED"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The chain is now unlocked."

    tag = "CHAIN_LOCKED"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The chain is now locked."

    tag = "NO_LOCKSITE"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "There is nothing here to which the chain can be locked."

    tag = "WANT_HINT"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "Do you want the hint?"

    tag = "TROLL_VICES"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "Gluttony is not one of the troll's vices.  Avarice, however, is."

    tag = "LAMP_DIM"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "Your lamp is getting dim.  You'd best start wrapping this up, unless\nyou can find some fresh batteries.  I seem to recall there's a vending\nmachine in the maze.  Bring some coins with you."

    tag = "LAMP_OUT"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "Your lamp has run out of power."

    tag = "PLEASE_ANSWER"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "Please answer the question."

    tag = "PIRATE_SPOTTED"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "There are faint rustling noises from the darkness behind you.  As you\nturn toward them, the beam of your lamp falls across a bearded pirate.\nHe is carrying a large chest.  \"Shiver me timbers!\" he cries, \"I've\nbeen spotted!  I'd best hie meself off to the maze to hide me chest!\"\nWith that, he vanishes into the gloom."

    tag = "GET_BATTERIES"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "Your lamp is getting dim.  You'd best go back for those batteries."

    tag = "REPLACE_BATTERIES"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "Your lamp is getting dim.  I'm taking the liberty of replacing the\nbatteries."

    tag = "MISSING_BATTERIES"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "Your lamp is getting dim, and you're out of spare batteries.  You'd\nbest start wrapping this up."

    tag = "REMOVE_MESSAGE"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "You sift your fingers through the dust, but succeed only in\nobliterating the cryptic message."

    tag = "CLUE_QUERY"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "Hmmm, this looks like a clue, which means it'll cost you 10 points to\nread it.  Should I go ahead and read it anyway?"

    tag = "WAYOUT_CLUE"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "It says, \"There is a way out of this place.  Do you need any more\ninformation to escape?  Sorry, but this initial hint is all you get.\""

    tag = "DONT_UNDERSTAND"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "I'm afraid I don't understand."

    tag = "HAND_PASSTHROUGH"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "Your hand passes through it as though it weren't there."

    tag = "PROD_DWARF"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "You prod the nearest dwarf, who wakes up grumpily, takes one look at\nyou, curses, and grabs for his axe."

    tag = "THIS_ACCEPTABLE"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "Is this acceptable?"

    tag = "OGRE_FULL"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The ogre doesn't appear to be hungry."

    tag = "OGRE_DODGE"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The ogre, who despite his bulk is quite agile, easily dodges your\nattack.  He seems almost amused by your puny effort."

    tag = "OGRE_PANIC1"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The ogre, distracted by your rush, is struck by the knife.  With a\nblood-curdling yell he turns and bounds after the dwarves, who flee\nin panic.  You are left alone in the room."

    tag = "OGRE_PANIC2"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The ogre, distracted by your rush, is struck by the knife.  With a\nblood-curdling yell he turns and bounds after the dwarf, who flees\nin panic.  You are left alone in the room."

    tag = "FREE_FLY"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The bird flies about agitatedly for a moment."

    tag = "CAGE_FLY"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The bird flies agitatedly about the cage."

    tag = "NECKLACE_FLY"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The bird flies about agitatedly for a moment, then disappears through\nthe crack.  It reappears shortly, carrying in its beak a jade\nnecklace, which it drops at your feet."

    tag = "WATER_URN"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "You empty the bottle into the urn, which promptly ejects the water\nwith uncanny accuracy, squirting you directly between the eyes."

    tag = "OIL_URN"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "Your bottle is now empty and the urn is full of oil."

    tag = "FULL_URN"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The urn is already full of oil."

    tag = "URN_NOPOUR"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "There's no way to get the oil out of the urn."

    tag = "URN_NOBUDGE"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The urn is far too firmly embedded for your puny strength to budge it."

    tag = "URN_GENIES"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "As you rub the urn, there is a flash of light and a genie appears.\nHis aspect is stern as he advises: \"One who wouldst traffic in\nprecious stones must first learn to recognize the signals thereof.\"\nHe wrests the urn from the stone, leaving a small cavity.  Turning to\nface you again, he fixes you with a steely eye and intones: \"Caution!\"\nGenie and urn vanish in a cloud of amber smoke.  The smoke condenses\nto form a rare amber gemstone, resting in the cavity in the rock."

    tag = "DOUGHNUT_HOLES"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "I suppose you collect doughnut holes, too?"

    tag = "GEM_FITS"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The gem fits easily into the cavity."

    tag = "RUG_RISES"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The Persian rug stiffens and rises a foot or so off the ground."

    tag = "RUG_WIGGLES"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The Persian rug draped over your shoulder seems to wriggle for a\nmoment, but then subsides."

    tag = "RUG_SETTLES"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The Persian rug settles gently to the ground."

    tag = "RUG_HOVERS"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The rug hovers stubbornly where it is."

    tag = "RUG_NOTHING1"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The rug does not appear inclined to cooperate."

    tag = "RUG_NOTHING2"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "If you mean to use the Persian rug, it does not appear inclined to\ncooperate."

    tag = "FLAP_ARMS"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "Though you flap your arms furiously, it is to no avail."

    tag = "RUG_GOES"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "You board the Persian rug, which promptly whisks you across the chasm.\nYou have time for a fleeting glimpse of a two thousand foot drop to a\nmighty river; then you find yourself on the other side."

    tag = "RUG_RETURNS"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The rug ferries you back across the chasm."

    tag = "ALL_SILENT"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "All is silent."

    tag = "STREAM_GURGLES"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The stream is gurgling placidly."

    tag = "WIND_WHISTLES"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The wind whistles coldly past your ears."

    tag = "STREAM_SPLASHES"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The stream splashes loudly into the pool."

    tag = "NO_MEANING"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "You are unable to make anything of the splashing noise."

    tag = "MURMURING_SNORING"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "You can hear the murmuring of the beanstalks and the snoring of the\ndwarves."

    tag = "SNAKES_HISSING"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "A loud hissing emanates from the snake pit."

    tag = "DULL_RUMBLING"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The air is filled with a dull rumbling sound."

    tag = "LOUD_ROAR"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The roar is quite loud here."

    tag = "TOTAL_ROAR"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The roaring is so loud that it drowns out all other sound."

    tag = "BIRD_CRAP"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The bird eyes you suspiciously and flutters away.  A moment later you\nfeel something wet land on your head, but upon looking up you can see\nno sign of the culprit."

    tag = "FEW_DROPS"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "There are only a few drops--not enough to carry."

    tag = "NOT_BRIGHT"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "(Uh, y'know, that wasn't very bright.)"

    tag = "TOOK_LONG"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "It's a pity you took so long about it."

    tag = "UPSTREAM_DOWNSTREAM"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "Upstream or downstream?"

    tag = "FOREST_QUERY"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = ""

    tag = "WATERS_CRASHING"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "The waters are crashing loudly against the shore."

    tag = "THROWN_KNIVES"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "%d of them throw knives at you!"

    tag = "MULTIPLE_HITS"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "%d of them get you!"

    tag = "ONE_HIT"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "One of them gets you!"

    tag = "NONE_HIT"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "None of them hits you!"

    tag = "DONT_KNOW"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "Sorry, I don't know the word \"%s\"."

    tag = "WHAT_DO"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "What do you want to do with the %s?"

    tag = "NO_SEE"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "I see no %s here."

    tag = "DO_WHAT"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "%s what?"

    tag = "OKEY_DOKEY"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "Okay, \"%s\"."

    tag = "GARNERED_POINTS"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "You have garnered %d out of a possible %d points, using %d turn%S."

    tag = "SUSPEND_WARNING"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "I can suspend your Adventure for you so that you can resume later, but\nit will cost you 5 points."

    tag = "HINT_COST"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "I am prepared to give you a hint, but it will cost you %d point%S."

    tag = "TOTAL_SCORE"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "You scored %d out of a possible %d, using %d turn%S."

    tag = "NEXT_HIGHER"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "To achieve the next higher rating, you need %d more point%S."

    tag = "NO_HIGHER"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "To achieve the next higher rating would be a neat trick!\nCongratulations!!"

    tag = "OFF_SCALE"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "You just went off my scale!!"

    tag = "RESUME_HELP"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "To resume your Adventure, start a new game and then say \"RESUME\"."

    tag = "RESUME_ABANDON"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "To resume an earlier Adventure, you must abandon the current one."

    tag = "VERSION_SKEW"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "I'm sorry, but that Adventure was begun using Version %d.%d of the\nsave file format, and this program uses Version %d.%d.  You must find an instance\nusing that other version in order to resume that Adventure."

    tag = "TWIST_TURN"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "Sorry, but the path twisted and turned so much that I can't figure\nout which way to go to get back."

    tag = "GO_UNNEEDED"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "You don't have to say \"go\" every time; just specify a direction or, if\nit's nearby, name the place to which you wish to move."

    tag = "NUMERIC_REQUIRED"
    arbitraryMessages.Seq = append(arbitraryMessages.Seq, tag)
    arbitraryMessages.Map[tag] = "This command requires a numeric argument."
    return arbitraryMessages
}

