// Code generated by yaml2go on 2022-08-16T20:50:00Z; DO NOT EDIT.

// Open Adventure - a clone of Open Adventure written in Go
// Copyright (c) 2022 Michael D Henderson
// SPDX-License-Identifier: BSD-2-clause

package state

// Motions is an ordered map of motion data.
// Use `Seq` to access sequentially or `Map` to access by key.
type Motions struct{
    Seq []*Motion            // sequential accessor
    Map map[string]*Motion   // tag accessor
}

// Motion is autogenerated
type Motion struct {
    Words    []string
    OldStyle bool
}

// generateMotions returns the initial state of motions
func generateMotions() *Motions{
    motions := Motions{
        Map: make(map[string]*Motion),
    }

    // seq: 0 name: MOT_0
    motion := &Motion{
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["MOT_0"] = motion

    // seq: 1 name: HERE
    motion = &Motion{
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["HERE"] = motion

    // seq: 2 name: MOT_2
    motion = &Motion{
        Words: []string{
            "road",
            "hill",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["MOT_2"] = motion

    // seq: 3 name: ENTER
    motion = &Motion{
        Words: []string{
            "enter",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["ENTER"] = motion

    // seq: 4 name: MOT_4
    motion = &Motion{
        Words: []string{
            "upstr",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["MOT_4"] = motion

    // seq: 5 name: MOT_5
    motion = &Motion{
        Words: []string{
            "downs",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["MOT_5"] = motion

    // seq: 6 name: MOT_6
    motion = &Motion{
        Words: []string{
            "fores",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["MOT_6"] = motion

    // seq: 7 name: FORWARD
    motion = &Motion{
        Words: []string{
            "forwa",
            "conti",
            "onwar",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["FORWARD"] = motion

    // seq: 8 name: BACK
    motion = &Motion{
        Words: []string{
            "back",
            "retur",
            "retre",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["BACK"] = motion

    // seq: 9 name: MOT_9
    motion = &Motion{
        Words: []string{
            "valle",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["MOT_9"] = motion

    // seq: 10 name: MOT_10
    motion = &Motion{
        Words: []string{
            "stair",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["MOT_10"] = motion

    // seq: 11 name: OUTSIDE
    motion = &Motion{
        Words: []string{
            "out",
            "outsi",
            "exit",
            "leave",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["OUTSIDE"] = motion

    // seq: 12 name: MOT_12
    motion = &Motion{
        Words: []string{
            "build",
            "house",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["MOT_12"] = motion

    // seq: 13 name: MOT_13
    motion = &Motion{
        Words: []string{
            "gully",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["MOT_13"] = motion

    // seq: 14 name: STREAM
    motion = &Motion{
        Words: []string{
            "strea",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["STREAM"] = motion

    // seq: 15 name: MOT_15
    motion = &Motion{
        Words: []string{
            "fork",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["MOT_15"] = motion

    // seq: 16 name: MOT_16
    motion = &Motion{
        Words: []string{
            "bed",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["MOT_16"] = motion

    // seq: 17 name: CRAWL
    motion = &Motion{
        Words: []string{
            "crawl",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["CRAWL"] = motion

    // seq: 18 name: MOT_18
    motion = &Motion{
        Words: []string{
            "cobbl",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["MOT_18"] = motion

    // seq: 19 name: INSIDE
    motion = &Motion{
        Words: []string{
            "inwar",
            "insid",
            "in",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["INSIDE"] = motion

    // seq: 20 name: MOT_20
    motion = &Motion{
        Words: []string{
            "surfa",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["MOT_20"] = motion

    // seq: 21 name: NUL
    motion = &Motion{
        Words: []string{
            "null",
            "nowhe",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["NUL"] = motion

    // seq: 22 name: MOT_22
    motion = &Motion{
        Words: []string{
            "dark",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["MOT_22"] = motion

    // seq: 23 name: MOT_23
    motion = &Motion{
        Words: []string{
            "passa",
            "tunne",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["MOT_23"] = motion

    // seq: 24 name: MOT_24
    motion = &Motion{
        Words: []string{
            "low",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["MOT_24"] = motion

    // seq: 25 name: MOT_25
    motion = &Motion{
        Words: []string{
            "canyo",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["MOT_25"] = motion

    // seq: 26 name: MOT_26
    motion = &Motion{
        Words: []string{
            "awkwa",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["MOT_26"] = motion

    // seq: 27 name: MOT_27
    motion = &Motion{
        Words: []string{
            "giant",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["MOT_27"] = motion

    // seq: 28 name: MOT_28
    motion = &Motion{
        Words: []string{
            "view",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["MOT_28"] = motion

    // seq: 29 name: UP
    motion = &Motion{
        Words: []string{
            "upwar",
            "up",
            "u",
            "above",
            "ascen",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["UP"] = motion

    // seq: 30 name: DOWN
    motion = &Motion{
        Words: []string{
            "d",
            "downw",
            "down",
            "desce",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["DOWN"] = motion

    // seq: 31 name: MOT_31
    motion = &Motion{
        Words: []string{
            "pit",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["MOT_31"] = motion

    // seq: 32 name: MOT_32
    motion = &Motion{
        Words: []string{
            "outdo",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["MOT_32"] = motion

    // seq: 33 name: MOT_33
    motion = &Motion{
        Words: []string{
            "crack",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["MOT_33"] = motion

    // seq: 34 name: MOT_34
    motion = &Motion{
        Words: []string{
            "steps",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["MOT_34"] = motion

    // seq: 35 name: MOT_35
    motion = &Motion{
        Words: []string{
            "dome",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["MOT_35"] = motion

    // seq: 36 name: LEFT
    motion = &Motion{
        Words: []string{
            "left",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["LEFT"] = motion

    // seq: 37 name: RIGHT
    motion = &Motion{
        Words: []string{
            "right",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["RIGHT"] = motion

    // seq: 38 name: MOT_38
    motion = &Motion{
        Words: []string{
            "hall",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["MOT_38"] = motion

    // seq: 39 name: MOT_39
    motion = &Motion{
        Words: []string{
            "jump",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["MOT_39"] = motion

    // seq: 40 name: MOT_40
    motion = &Motion{
        Words: []string{
            "barre",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["MOT_40"] = motion

    // seq: 41 name: MOT_41
    motion = &Motion{
        Words: []string{
            "over",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["MOT_41"] = motion

    // seq: 42 name: MOT_42
    motion = &Motion{
        Words: []string{
            "acros",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["MOT_42"] = motion

    // seq: 43 name: EAST
    motion = &Motion{
        Words: []string{
            "east",
            "e",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["EAST"] = motion

    // seq: 44 name: WEST
    motion = &Motion{
        Words: []string{
            "west",
            "w",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["WEST"] = motion

    // seq: 45 name: NORTH
    motion = &Motion{
        Words: []string{
            "north",
            "n",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["NORTH"] = motion

    // seq: 46 name: SOUTH
    motion = &Motion{
        Words: []string{
            "south",
            "s",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["SOUTH"] = motion

    // seq: 47 name: NE
    motion = &Motion{
        Words: []string{
            "ne",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["NE"] = motion

    // seq: 48 name: SE
    motion = &Motion{
        Words: []string{
            "se",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["SE"] = motion

    // seq: 49 name: SW
    motion = &Motion{
        Words: []string{
            "sw",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["SW"] = motion

    // seq: 50 name: NW
    motion = &Motion{
        Words: []string{
            "nw",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["NW"] = motion

    // seq: 51 name: MOT_51
    motion = &Motion{
        Words: []string{
            "debri",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["MOT_51"] = motion

    // seq: 52 name: MOT_52
    motion = &Motion{
        Words: []string{
            "hole",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["MOT_52"] = motion

    // seq: 53 name: MOT_53
    motion = &Motion{
        Words: []string{
            "wall",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["MOT_53"] = motion

    // seq: 54 name: MOT_54
    motion = &Motion{
        Words: []string{
            "broke",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["MOT_54"] = motion

    // seq: 55 name: MOT_55
    motion = &Motion{
        Words: []string{
            "y2",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["MOT_55"] = motion

    // seq: 56 name: MOT_56
    motion = &Motion{
        Words: []string{
            "climb",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["MOT_56"] = motion

    // seq: 57 name: LOOK
    motion = &Motion{
        Words: []string{
            "l",
            "x",
            "look",
            "exami",
            "touch",
            "descr",
        },
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["LOOK"] = motion

    // seq: 58 name: MOT_58
    motion = &Motion{
        Words: []string{
            "floor",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["MOT_58"] = motion

    // seq: 59 name: MOT_59
    motion = &Motion{
        Words: []string{
            "room",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["MOT_59"] = motion

    // seq: 60 name: MOT_60
    motion = &Motion{
        Words: []string{
            "slit",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["MOT_60"] = motion

    // seq: 61 name: MOT_61
    motion = &Motion{
        Words: []string{
            "slab",
            "slabr",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["MOT_61"] = motion

    // seq: 62 name: XYZZY
    motion = &Motion{
        Words: []string{
            "xyzzy",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["XYZZY"] = motion

    // seq: 63 name: DEPRESSION
    motion = &Motion{
        Words: []string{
            "depre",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["DEPRESSION"] = motion

    // seq: 64 name: ENTRANCE
    motion = &Motion{
        Words: []string{
            "entra",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["ENTRANCE"] = motion

    // seq: 65 name: PLUGH
    motion = &Motion{
        Words: []string{
            "plugh",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["PLUGH"] = motion

    // seq: 66 name: MOT_66
    motion = &Motion{
        Words: []string{
            "secre",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["MOT_66"] = motion

    // seq: 67 name: CAVE
    motion = &Motion{
        Words: []string{
            "cave",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["CAVE"] = motion

    // seq: 68 name: CROSS
    motion = &Motion{
        Words: []string{
            "cross",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["CROSS"] = motion

    // seq: 69 name: BEDQUILT
    motion = &Motion{
        Words: []string{
            "bedqu",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["BEDQUILT"] = motion

    // seq: 70 name: PLOVER
    motion = &Motion{
        Words: []string{
            "plove",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["PLOVER"] = motion

    // seq: 71 name: ORIENTAL
    motion = &Motion{
        Words: []string{
            "orien",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["ORIENTAL"] = motion

    // seq: 72 name: CAVERN
    motion = &Motion{
        Words: []string{
            "caver",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["CAVERN"] = motion

    // seq: 73 name: SHELLROOM
    motion = &Motion{
        Words: []string{
            "shell",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["SHELLROOM"] = motion

    // seq: 74 name: RESERVOIR
    motion = &Motion{
        Words: []string{
            "reser",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["RESERVOIR"] = motion

    // seq: 75 name: OFFICE
    motion = &Motion{
        Words: []string{
            "main",
            "offic",
        },
        OldStyle: true,
    }
    motions.Seq = append(motions.Seq, motion)
    motions.Map["OFFICE"] = motion

    return &motions
}

