// Code generated by yaml2go on 2022-08-17T04:50:23Z; DO NOT EDIT.

// Open Adventure - a clone of Open Adventure written in Go
// Copyright (c) 2022 Michael D Henderson
// SPDX-License-Identifier: BSD-2-clause

package state

// Obituary is data
type Obituary struct {
    Query       []string
    YesResponse []string
}

// generateObituaries returns the initial state of obituaries
func generateObituaries() []*Obituary {
    return []*Obituary{
        &Obituary{
            Query: []string{
                "Oh dear, you seem to have gotten yourself killed.  I might be able to",
                "help you out, but I've never really done this before.  Do you want me",
                "to try to reincarnate you?",
            },
            YesResponse: []string{
                "All right.  But don't blame me if something goes wr......",
                "                    --- POOF!! ---",
                "You are engulfed in a cloud of orange smoke.  Coughing and gasping,",
                "you emerge from the smoke and find....",
            },
        },
        &Obituary{
            Query: []string{
                "You clumsy oaf, you've done it again!  I don't know how long I can",
                "keep this up.  Do you want me to try reincarnating you again?",
            },
            YesResponse: []string{
                "Okay, now where did I put my orange smoke?....  >POOF!<",
                "Everything disappears in a dense cloud of orange smoke.",
            },
        },
        &Obituary{
            Query: []string{
                "Now you've really done it!  I'm out of orange smoke!  You don't expect",
                "me to do a decent reincarnation without any orange smoke, do you?",
            },
            YesResponse: []string{
                "Okay, if you're so smart, do it yourself!  I'm leaving!",
            },
        },
   }
}

