// Code generated by yaml2go on 2022-08-16T20:50:00Z; DO NOT EDIT.

// Open Adventure - a clone of Open Adventure written in Go
// Copyright (c) 2022 Michael D Henderson
// SPDX-License-Identifier: BSD-2-clause

package state

// TurnThreshold is autogenerated
type TurnThreshold struct {
    Threshold int
    PointLoss int
    Message   []string
}

// generateTurnThresholds returns the initial state for turn thresholds
func generateTurnThresholds() []*TurnThreshold {
    return []*TurnThreshold{
        &TurnThreshold{
            Threshold: 350,
            PointLoss: 2,
            Message: []string{
                "Tsk!  A wizard wouldn't have to take 350 turns.  This is going to cost",
                "you a couple of points.",
            },
        },
        &TurnThreshold{
            Threshold: 500,
            PointLoss: 3,
            Message: []string{
                "500 turns?  That's another few points you've lost.",
            },
        },
        &TurnThreshold{
            Threshold: 1000,
            PointLoss: 5,
            Message: []string{
                "Are you still at it?  Five points off for exceeding 1000 turns!",
            },
        },
        &TurnThreshold{
            Threshold: 2500,
            PointLoss: 10,
            Message: []string{
                "Good grief, don't you *EVER* give up?  Do you realize you've spent",
                "over 2500 turns at this?  That's another ten points off, a total of",
                "twenty points lost for taking so long.",
            },
        },
    }
}

