/*
 * Open Adventure - a clone of Open Adventure written in Go
 * Copyright (c) 2022 Michael D Henderson
 * SPDX-License-Identifier: BSD-2-clause
 */

package main

import (
	"fmt"
	"io"
	"strings"
)

// TURNTHRESHOLD is used to load the YAML data for turn thresholds
type TURNTHRESHOLD struct {
	Threshold int
	PointLoss int `yaml:"point_loss"`
	Message   string
}

// GenerateTurnThresholds convert turn thresholds to go code.
func (y *YAML) GenerateTurnThresholds(w io.Writer) error {
	_, _ = fmt.Fprintf(w, "// TurnThreshold is autogenerated\n")
	_, _ = fmt.Fprintf(w, "type TurnThreshold struct {\n")
	_, _ = fmt.Fprintf(w, "    Threshold int\n")
	_, _ = fmt.Fprintf(w, "    PointLoss int\n")
	_, _ = fmt.Fprintf(w, "    Message   []string\n")
	_, _ = fmt.Fprintf(w, "}\n\n")

	_, _ = fmt.Fprintf(w, "// generateTurnThresholds returns the initial state for turn thresholds\n")
	_, _ = fmt.Fprintf(w, "func generateTurnThresholds() []*TurnThreshold {\n")
	_, _ = fmt.Fprintf(w, "    return []*TurnThreshold{\n")
	for _, v := range y.TurnThresholds {
		_, _ = fmt.Fprintf(w, "        &TurnThreshold{\n")
		if v.Threshold != 0 {
			_, _ = fmt.Fprintf(w, "            Threshold: %d,\n", v.Threshold)
		}
		if v.PointLoss != 0 {
			_, _ = fmt.Fprintf(w, "            PointLoss: %d,\n", v.PointLoss)
		}
		if len(v.Message) != 0 {
			_, _ = fmt.Fprintf(w, "            Message: []string{\n")
			for _, s := range strings.Split(v.Message, "\n") {
				_, _ = fmt.Fprintf(w, "                %q,\n", s)
			}
			_, _ = fmt.Fprintf(w, "            },\n")
		}
		_, _ = fmt.Fprintf(w, "        },\n")
	}
	_, _ = fmt.Fprintf(w, "    }\n")
	_, _ = fmt.Fprintf(w, "}\n")
	_, _ = fmt.Fprintf(w, "\n")

	return nil
}
